### ISSUE TITLE
`Error : invalid json response body at https://revuto.com/api/v1/auth/register reason: Unexpected token < in JSON at position 0`

### ISSUE THREAD

**Issue by lorcalhost** [cdw1p/revuto.com-Auto#1]
No success, at every cycle I get the following error:
`[18:49:10] Error : invalid json response body at https://revuto.com/api/v1/auth/register reason: Unexpected token < in JSON at position 0`

**Comment by cdw1p** [comment]
api response has updated

**Comment by lorcalhost** [comment]
I see, thank you anyway.
